import { Platform, StyleSheet } from 'react-native';

export const paletteV2 = {
  primaryDark: '#004A3F',
  primaryMain: '#00796B',
  primaryLight: '#4DB6AC',
  primaryLighter: '#A7D8D4',
  primaryUltraLight: '#E0F2F1',

  accentMain: '#FF7043',
  accentLight: '#FFAB91',
  accentGradient: ['#FF7043', '#FF8A65'] as const,

  gradientPrimaryButton: ['#00796B', '#00645A'] as const,
  gradientAccentButton: ['#00897B', '#00695C'] as const,
  gradientDisabled: ['#B0BEC5', '#9E9E9E'] as const,

  neutralDarker: '#1B2B34',
  neutralDark: '#344955',
  neutralMedium: '#566573',
  neutralLight: '#90A4AE',
  neutralExtraLight: '#D4D8DC',
  neutralUltraLight: '#F5F7F8',
  neutralWhite: '#FFFFFF',

  iconDefault: '#566573',

  backgroundPage: '#F4F7F6',
  surfaceNav: '#FFFFFF',
  surfaceCard: '#FFFFFF',

  errorMain: '#E53935',
  errorLight: '#FFEBEE',
  successMain: '#388E3C',
  successLight: '#E8F5E9',
  warningMain: '#FFB300',
  warningLight: '#FFFDE7',

  textPrimaryOnLight: '#1B2B34',
  textSecondaryOnLight: '#566573',
  textPlaceholderOnLight: '#90A4AE',

  textPrimaryOnDark: '#FFFFFF',
  textSecondaryOnDark: '#E0E0E0',

  borderFocus: '#00796B',
  borderDefault: '#CFD8DC',
  borderLight: '#E0E0E0',
  shadowColor: '#1B2B34',
};

export const styles = StyleSheet.create({
  bgSurface: { backgroundColor: paletteV2.surfaceNav },
  iconDisabled: { color: paletteV2.neutralLight },
  iconSubtle: { color: paletteV2.neutralMedium },
  textPlaceholder: { color: paletteV2.textPlaceholderOnLight },

  mainContentContainer: {
    flex: 1,
    backgroundColor: paletteV2.backgroundPage,
  },
  scrollableContentArea: {
    flex: 1,
  },
  fullScreenLoaderContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: paletteV2.backgroundPage,
  },
  loadingText: {
    marginTop: 20,
    fontSize: 18,
    color: paletteV2.neutralDark,
    fontWeight: '500',
  },
  topNavWrapper: {
    paddingVertical: 12,
    minHeight: 60,
    justifyContent: 'center',
  },
  searchBarContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    height: 48,
  },
  searchBar: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: paletteV2.neutralUltraLight,
    borderRadius: 24,
    paddingHorizontal: 16,
    height: '100%',
    borderWidth: 1,
    borderColor: paletteV2.borderDefault,
  },
  searchInput: {
    flex: 1,
    fontSize: 16,
    color: paletteV2.textPrimaryOnLight,
    marginLeft: 10,
  },
  searchIconPrefix:{
    marginRight: 0,
  },
  filterSortButton: {
    padding: 10,
    marginLeft: 12,
    borderRadius: 24,
    backgroundColor: paletteV2.primaryUltraLight,
    alignItems: 'center',
    justifyContent: 'center',
    width: 48,
    height: 48,
  },
  sortOptionsSingleRowContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 0,
    height: 48,
  },
  sortByLabelCompact: {
    color: paletteV2.textSecondaryOnLight,
    fontSize: 15,
    fontWeight: '500',
    marginRight: 10,
  },
  sortButtonsScrollContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 6,
  },
  sortOptionButtonCompact: {
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 20,
    backgroundColor: paletteV2.neutralUltraLight,
    borderWidth: 1.5,
    borderColor: paletteV2.borderDefault,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
  },
  sortOptionButtonActiveCompact: {
    backgroundColor: paletteV2.primaryLighter,
    borderColor: paletteV2.primaryMain,
  },
  sortOptionButtonTextCompact: {
    color: paletteV2.neutralDark,
    fontWeight: '500',
    fontSize: 14,
  },
  sortOptionButtonTextActiveCompact: {
    color: paletteV2.primaryDark,
    fontWeight: '600',
  },
  sortIconCompact: {
    marginLeft: 6,
  },
  closeSortButtonCompact: {
    padding: 10,
    marginLeft: 'auto',
  },
  listContainer: {
    paddingHorizontal: 16,
    paddingTop: 20,
    paddingBottom: Platform.OS === 'ios' ? 230 : 210,
  },
  employeeCard: {
    backgroundColor: paletteV2.surfaceCard,
    borderRadius: 16,
    marginBottom: 18,
    shadowColor: paletteV2.shadowColor,
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 7,
    borderWidth: 1,
    borderColor: paletteV2.borderLight,
  },
  employeeCardActive: {
    elevation: 12,
    shadowOpacity: 0.15,
    borderColor: paletteV2.primaryMain,
    borderWidth: 2,
  },
  cardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 18,
    paddingTop: 18,
    paddingBottom: 14,
  },
  employeeImage: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: paletteV2.neutralUltraLight,
    marginRight: 16,
    borderWidth: 1.5,
    borderColor: paletteV2.primaryLighter,
  },
  employeeMainInfo: {
    flex: 1,
  },
  employeeNameText: {
    fontSize: 18,
    fontWeight: '600',
    color: paletteV2.textPrimaryOnLight,
    marginBottom: 2,
  },
  employeeEmailText: {
    fontSize: 14,
    color: paletteV2.textSecondaryOnLight,
  },
  menuButton: {
    padding: 10,
    borderRadius: 22,
  },
  menuDropdown: {
    position: 'absolute',
    top: 65,
    right: 18,
    backgroundColor: paletteV2.surfaceCard,
    borderRadius: 14,
    shadowColor: paletteV2.shadowColor,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.18,
    shadowRadius: 15,
    elevation: 12,
    zIndex: 2000,
    width: 280,
    borderWidth: 1,
    borderColor: paletteV2.borderLight,
  },
  menuItemTouchable: {
    justifyContent: 'center',
  },
  menuItemContent: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 15,
    paddingHorizontal:20,
  },
  menuItemIcon: {
    marginRight: 18,
    width: 22,
  },
  menuItemIconDefault: {
    color: paletteV2.neutralDark,
  },
  menuItemText: {
    fontSize: 15.5,
    color: paletteV2.textPrimaryOnLight,
    flex: 1,
    fontWeight: '500',
  },
  menuDivider: {
    height: 1,
    backgroundColor: paletteV2.borderLight,
    marginHorizontal: 18,
  },
  menuItemTextDestructive: {
    fontSize: 15.5,
    color: paletteV2.errorMain,
    fontWeight: '500',
    flex: 1,
  },
  menuItemTextDestructiveSimple: {
    fontSize: 15.5,
    color: paletteV2.warningMain,
    fontWeight: '500',
    flex: 1,
  },
  cardDetails: {
    paddingHorizontal: 20,
    paddingBottom: 14,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: paletteV2.borderLight,
  },
  detailItemRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 9,
  },
  detailLabel: {
    fontSize: 14,
    color: paletteV2.textSecondaryOnLight,
    fontWeight: '500',
  },
  detailValue: {
    fontSize: 14.5,
    color: paletteV2.textPrimaryOnLight,
    fontWeight: '500',
    textAlign: 'right',
    flexShrink: 1,
    marginLeft: 10,
  },
  viewDetailsButton: {
    flexDirection: 'row',
    marginTop: 14,
    marginHorizontal: 20,
    marginBottom: 20,
    backgroundColor: paletteV2.primaryUltraLight,
    paddingVertical: 14,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1.5,
    borderColor: paletteV2.primaryLighter,
  },
  viewDetailsButtonText: {
    color: paletteV2.primaryDark,
    fontWeight: '600',
    fontSize: 15,
  },
  noDataContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 35,
    paddingBottom: 90,
  },
  noDataTitle: {
    fontSize: 24,
    fontWeight: '600',
    color: paletteV2.neutralDarker,
    marginTop: 28,
    marginBottom: 14,
    textAlign: 'center',
  },
  noDataTextDetail: {
    fontSize: 16,
    color: paletteV2.neutralMedium,
    textAlign: 'center',
    marginBottom: 35,
    lineHeight: 24,
  },
  addNewFromEmptyStateButton: {
    flexDirection: 'row',
    paddingVertical: 16,
    paddingHorizontal: 35,
    borderRadius: 28,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: paletteV2.primaryDark,
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 8,
  },
  addNewFromEmptyStateButtonText: {
    color: paletteV2.textPrimaryOnDark,
    fontWeight: '600',
    fontSize: 17,
    marginLeft: 12,
  },
  addEmployeeFabTouchable: {
    position: 'absolute',
    right: 28,
    bottom: Platform.OS === 'ios' ? 80 : 65,
    zIndex: 1000,
  },
  addEmployeeFab: {
    width: 64,
    height: 64,
    borderRadius: 32,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: paletteV2.accentMain,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.35,
    shadowRadius: 8,
    elevation: 12,
  },
  pagination: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderTopWidth: 1,
    borderTopColor: paletteV2.borderLight,
    backgroundColor: paletteV2.surfaceNav,
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    shadowColor: paletteV2.shadowColor,
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 5,
  },
  paginationNavButton: {
    padding: 12,
    borderRadius: 22,
  },
  pageInfo: {
    fontSize: 15,
    fontWeight: '500',
    color: paletteV2.neutralDark,
    marginHorizontal: 10,
  },
  itemsPerPageWrapper: {
    position: 'relative',
  },
  itemsPerPageDropdownTrigger: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: paletteV2.neutralUltraLight,
    paddingVertical: 9,
    paddingHorizontal: 14,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: paletteV2.borderDefault,
  },
  itemsPerPageCurrentText: {
    fontSize: 15,
    fontWeight: '500',
    color: paletteV2.textPrimaryOnLight,
    marginRight: 5,
  },
  itemsPerPageDropdownOptions: {
    position: 'absolute',
    bottom: '100%',
    marginBottom: 10,
    right: 0,
    backgroundColor: paletteV2.surfaceCard,
    borderRadius: 12,
    borderColor: paletteV2.borderDefault,
    borderWidth: 1,
    shadowColor: paletteV2.shadowColor,
    shadowOffset: { width: 0, height: -5 },
    shadowOpacity: 0.12,
    shadowRadius: 10,
    elevation: 10,
    width: 170,
    zIndex: 2000,
  },
  itemsPerPageDropdownOptionItem: {
    paddingVertical: 14,
    paddingHorizontal: 18,
  },
  itemsPerPageDropdownOptionText: {
    fontSize: 15,
    color: paletteV2.textPrimaryOnLight,
  },
  itemsPerPageOptionTextActive: {
    color: paletteV2.primaryMain,
    fontWeight: '600',
  },

  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(20, 30, 40, 0.88)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: Platform.OS === 'web' ? 24 : 10,
  },
  modalContent: {
    backgroundColor: paletteV2.surfaceCard,
    borderRadius: 20,
    padding: 0,
    width: Platform.OS === 'web' ? 700 : '100%',
    maxWidth: 720,
    maxHeight: '92%',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.3,
    shadowRadius: 25,
    elevation: 20,
    overflow: 'hidden',
  },
  formHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingTop: 10,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: paletteV2.borderLight,
  },
  formCloseButton: {
    padding: 10,
    borderRadius: 20,
  },
  formScrollView: {
    paddingHorizontal: 24,
    paddingTop: 12,
    paddingBottom: 24,
  },
  formTitle: {
    fontSize: 20,
    fontWeight: '600',
    color: paletteV2.primaryDark,
  },
  formLabel: {
    fontSize: 14,
    color: paletteV2.textSecondaryOnLight,
    marginBottom: 8,
    fontWeight: '500',
    marginTop: 16,
  },
  requiredIndicator: {
    color: paletteV2.errorMain,
    marginLeft: 3,
  },
  formInput: {
    backgroundColor: paletteV2.neutralWhite,
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 14,
    fontSize: 16,
    color: paletteV2.textPrimaryOnLight,
    borderWidth: 1.5,
    borderColor: paletteV2.borderDefault,
  },
  formInputError: {
    borderColor: paletteV2.errorMain,
    backgroundColor: paletteV2.errorLight,
    borderWidth: 1.5,
  },
  formErrorText: {
    fontSize: 13,
    color: paletteV2.errorMain,
    marginTop: 6,
    marginBottom: 8,
  },
  formGeneralErrorText: {
    textAlign: 'center',
    marginBottom: 16,
    fontWeight: '500'
  },
  disabledInput: {
    backgroundColor: paletteV2.neutralUltraLight,
    color: paletteV2.neutralMedium,
    borderColor: paletteV2.borderLight,
  },
  formRow: {
    flexDirection: 'row',
    gap: 16,
  },
  formColumn: {
    flex: 1,
  },
  checkboxContainer: {
    flexDirection: 'column',
    alignItems: 'flex-start',
    marginBottom: 16,
    marginTop: 12,
  },
  checkboxTouchable: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 6,
  },
  checkboxIcon: {
    marginRight: 12,
  },
  checkboxLabel: {
    fontSize: 15,
    color: paletteV2.textPrimaryOnLight,
    fontWeight: '500',
  },
  derivedInfoLabel: {
    fontSize: 13,
    color: paletteV2.neutralMedium,
    marginLeft: 0,
    marginTop: 3,
    fontStyle: 'italic',
  },
  radioGroup: {
    flexDirection: 'row',
    marginBottom: 16,
    marginTop: 8,
    gap: 12,
  },
  radioButtonContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 10,
    borderWidth: 1.5,
    borderColor: paletteV2.borderDefault,
    backgroundColor: paletteV2.neutralWhite,
    flex: 1,
    justifyContent: 'center',
  },
  radioButtonActive: {
    borderColor: paletteV2.primaryMain,
    backgroundColor: paletteV2.primaryUltraLight,
    borderWidth: 1.5,
  },
  radioButtonDisabled: {
    backgroundColor: paletteV2.neutralUltraLight,
    borderColor: paletteV2.borderLight,
    opacity: 0.75,
  },
  radioLabel: {
    marginLeft: 10,
    fontSize: 15,
    color: paletteV2.textPrimaryOnLight,
    fontWeight: '500',
  },
  formActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    marginTop: 28,
    borderTopWidth: 1,
    borderTopColor: paletteV2.borderLight,
    paddingTop: 22,
    gap: 12,
  },
  formButtonBase: {
    borderRadius: 25,
    minWidth: 130,
    height: 50,
    alignItems: 'center',
    justifyContent: 'center',
  },
  submitButtonGradient: {
    paddingVertical: 14,
    paddingHorizontal: 24,
    borderRadius: 25,
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 4,
    width: '100%',
    height: '100%',
  },
  submitButtonDisabled: {
    opacity: 0.7,
  },
  cancelButton: {
    backgroundColor: paletteV2.neutralWhite,
    borderWidth: 1.5,
    borderColor: paletteV2.borderDefault,
  },
  cancelButtonText: {
    color: paletteV2.neutralDark,
    fontWeight: '600',
    fontSize: 15,
  },
  formButtonText: {
    color: paletteV2.textPrimaryOnDark,
    fontSize: 15,
    fontWeight: '600',
  },
  confirmModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(20, 30, 40, 0.9)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 24,
  },
  confirmModalContent: {
    backgroundColor: paletteV2.surfaceCard,
    borderRadius: 18,
    paddingHorizontal: 24,
    paddingTop: 28,
    paddingBottom: 24,
    width: Platform.OS === 'web' ? 420 : '90%',
    maxWidth: 450,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.25,
    shadowRadius: 15,
    elevation: 15,
    alignItems: 'center',
  },
  confirmModalIconContainer: {
    marginBottom: 18,
    width: 70,
    height: 70,
    borderRadius: 35,
    backgroundColor: paletteV2.neutralUltraLight,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: paletteV2.borderLight,
  },
  confirmModalTitle: {
    fontSize: 20,
    fontWeight: '600',
    color: paletteV2.neutralDarker,
    marginBottom: 12,
    textAlign: 'center',
  },
  confirmModalMessage: {
    fontSize: 15,
    color: paletteV2.neutralMedium,
    textAlign: 'center',
    lineHeight: 22,
    marginBottom: 20,
  },
  resignationDateContainer: {
    width: '100%',
    marginBottom: 24,
  },
  confirmModalActions: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
    marginTop: 10,
  },
  confirmModalButton: {
    borderRadius: 25,
    paddingVertical: 13,
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    height: 50,
  },
  confirmModalCancelButton: {
    backgroundColor: paletteV2.neutralExtraLight,
    marginRight: 8,
    borderWidth: 1.5,
    borderColor: paletteV2.borderDefault,
  },
  confirmModalCancelButtonText: {
    color: paletteV2.neutralDark,
    fontWeight: '600',
    fontSize: 15,
  },
  confirmModalDeleteButtonWarn: {
    backgroundColor: paletteV2.warningMain,
    marginLeft: 8,
  },
  confirmModalDeleteButtonDestructive: {
    backgroundColor: paletteV2.errorMain,
    marginLeft: 8,
  },
  confirmModalButtonText: {
    color: paletteV2.textPrimaryOnDark,
    fontSize: 15,
    fontWeight: '600',
  },
  profileImageModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.85)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  profileImageModalContent: {
    width: '90%',
    height: '70%',
    borderRadius: 10,
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
  },
  profileImageModalImage: {
    width: '100%',
    height: '100%',
  },
  profileImageModalCloseButton: {
    position: 'absolute',
    top: Platform.OS === 'ios' ? 40 : 20,
    right: 0,
    padding: 10,
    zIndex: 1,
  },
  
});