export const styles = {
  container: { padding: 16, backgroundColor: '#f9f9f9', paddingBottom: 50 },
  centeredView: { flex: 1, justifyContent: 'center', alignItems: 'center' as 'center', backgroundColor: '#f9f9f9' },
  loadingText: { marginTop: 10, fontSize: 16, color: '#555' },
  fieldContainer: { marginBottom: 18 },
  label: { marginBottom: 6, fontWeight: '600' as '600', fontSize: 15, color: '#333' },
  requiredIndicator: { color: 'red' },
  input: { borderWidth: 1, borderColor: '#ccc', paddingVertical: 10, paddingHorizontal: 12, borderRadius: 8, backgroundColor: 'white', fontSize: 16, color: '#333' },
  textarea: { borderWidth: 1, borderColor: '#ccc', paddingVertical: 10, paddingHorizontal: 12, borderRadius: 8, minHeight: 100, textAlignVertical: 'top' as 'top', backgroundColor: 'white', fontSize: 16, color: '#333' },
  readonlyInput: { backgroundColor: '#e9e9e9', color: '#777' },
  errorInput: { borderColor: '#d9534f', borderWidth: 2 },
  errorText: { color: '#d9534f', marginTop: 6, fontSize: 13, fontWeight: '500' as '500' },
  datePickerButton: { justifyContent: 'center' as 'center', minHeight: 48 },
  pickerContainer: { borderWidth: 1, borderColor: '#ccc', borderRadius: 8, backgroundColor: 'white' },
  profilePicContainer: { alignItems: 'center' as 'center', marginBottom: 20, marginTop: 10 },
  profilePicWrapper: { 
    width: 120, 
    height: 120, 
    borderRadius: 60, 
    justifyContent: 'center' as 'center', 
    alignItems: 'center' as 'center' 
  },
  profilePic: { width: 120, height: 120, borderRadius: 60, borderWidth: 2, borderColor: '#ddd', backgroundColor: '#e0e0e0' },
  profilePicLoaderOverlay: {
    position: 'absolute' as 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.4)',
    borderRadius: 60,
    justifyContent: 'center' as 'center',
    alignItems: 'center' as 'center',
  },
  uploadButton: { marginTop: 10, backgroundColor: '#90D1CA', paddingVertical: 8, paddingHorizontal: 15, borderRadius: 5 },
  uploadButtonText: { color: '#fff', fontSize: 14, fontWeight: 'bold' as 'bold' },
  profilePicErrorText: { color: 'red', marginTop: 5, fontSize: 12 },
};
