import { StyleSheet } from 'react-native';

const paletteV2 = {
  primaryMain: '#5DBBAD',
  primaryDark: '#3E9C90',
  primaryLight: '#A7D7D3',
  accentMain: '#FCA311',
  backgroundLight: '#F8F9FA',
  surface: '#FFFFFF',
  textPrimaryOnLight: '#4A5568',
  textSecondaryOnLight: '#6B7280',
  textDisabled: '#9CA3AF',
  textPrimaryOnDark: '#FFFFFF',
  errorMain: '#E53935',
  warningMain: '#FFB300',
  successMain: '#43A047',
  iconDefault: '#8FA3AD',
  iconSubtle: '#B0BEC5',
  neutralDark: '#6A7881',
  neutralLight: '#ECEFF1',
  neutralMedium: '#9CA3AF',
  neutralWhite: '#FFFFFF',
  gradientPrimaryButton: ['#5DBBAD', '#3E9C90'],
};

export const styles = StyleSheet.create({
  container: { 
    flexGrow: 1, 
    padding: 20, 
    backgroundColor: paletteV2.backgroundLight, 
  },
  loaderContainer: { 
    flex: 1, 
    justifyContent: 'center', 
    alignItems: 'center', 
    backgroundColor: paletteV2.backgroundLight, 
    paddingHorizontal: 20, 
  },
  errorText: { 
    fontSize: 18, 
    color: paletteV2.errorMain, 
    marginTop: 16, 
    textAlign: 'center', 
    fontWeight: '500',
  },
  retryButton: { 
    marginTop: 24, 
    backgroundColor: paletteV2.primaryMain, 
    paddingVertical: 12, 
    paddingHorizontal: 24, 
    borderRadius: 8, 
    elevation: 2,
  },
  retryButtonText: { 
    color: paletteV2.textPrimaryOnDark, 
    fontSize: 16, 
    fontWeight: '600', 
  },
  headerBar: { 
    flexDirection: 'row', 
    alignItems: 'center', 
    justifyContent: 'space-between', 
    width: '100%', 
    height: 60,
    paddingHorizontal: 12, 
    backgroundColor: paletteV2.surface,
    borderBottomWidth: 1,
    borderBottomColor: paletteV2.neutralLight,
  },
  headerNavButton: { 
    padding: 8, 
    minWidth: 44, 
    minHeight: 44,
    alignItems: 'center',
    justifyContent: 'center'
  },
  headerTitleContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 8,
  },
  headerTitleText: { 
    fontSize: 20, 
    fontWeight: 'bold', 
    color: paletteV2.textPrimaryOnLight,
    textAlign: 'center',
  },
  headerSubtitleText: {
    fontSize: 13,
    color: paletteV2.textSecondaryOnLight,
    textAlign: 'center',
    marginTop: 2,
  },
  headerActions: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  logoutButtonContainer: {
    marginLeft: 4,
  },
  section: { 
    backgroundColor: paletteV2.surface, 
    borderRadius: 12, 
    padding: 18, 
    marginBottom: 20, 
    elevation: 1, 
    shadowColor: paletteV2.neutralDark, 
    shadowOffset: { width: 0, height: 2 }, 
    shadowOpacity: 0.05, 
    shadowRadius: 4, 
  },
  sectionTitle: { 
    fontSize: 19, 
    fontWeight: 'bold', 
    color: paletteV2.primaryDark, 
    marginBottom: 18, 
    paddingBottom: 10,
    borderBottomWidth: 2,
    borderBottomColor: paletteV2.primaryLight,
  },
  row: { 
    flexDirection: 'row', 
    marginBottom: 0, 
    marginHorizontal: -6, 
  },
  column: { 
    flex: 1, 
    paddingHorizontal: 6, 
  },
  fullColumn: { 
    flex: 1,
    width: '100%',
  },
  fieldContainer: { 
    marginBottom: 16,
    flexDirection: 'column',
  },
  fieldContainerFullWidth:{ 
    width: '100%',
  },
  label: { 
    fontSize: 13, 
    fontWeight: '600', 
    color: '#D3D3D3', 
    marginBottom: 6, 
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  value: { 
    fontSize: 16, 
    color: paletteV2.textPrimaryOnLight, 
    fontWeight: '500',
  },
  profileHeaderMain: { 
    alignItems: 'center', 
    marginBottom: 28, 
  },
  avatarContainer: { 
    width: 110, 
    height: 110, 
    borderRadius: 55, 
    backgroundColor: paletteV2.neutralLight, 
    justifyContent: 'center', 
    alignItems: 'center',
    borderWidth: 4,
    borderColor: paletteV2.primaryLight,
    overflow: 'hidden',
    marginBottom: 18,
    elevation: 3,
    shadowColor: paletteV2.neutralDark,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
  },
  avatar: { 
    width: '100%', 
    height: '100%', 
  },
  imageLoader: {
    position: 'absolute',
  },
  actionButton: { 
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: paletteV2.primaryMain,
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 25,
    elevation: 2,
    shadowColor: paletteV2.primaryDark,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
  },
  actionButtonText: {
    color: paletteV2.textPrimaryOnDark,
    fontWeight: 'bold',
    fontSize: 15,
  },
  contactItemContainer: {
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: paletteV2.neutralLight,
  },
  lastContactItemContainer: {
    borderBottomWidth: 0,
  },
  noDataText: {
    fontSize: 15,
    color: paletteV2.textSecondaryOnLight,
    textAlign: 'center',
    paddingVertical: 15,
    fontStyle: 'italic',
  },
  documentItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 14,
    paddingHorizontal: 12,
    marginBottom: 10,
    backgroundColor: paletteV2.neutralWhite, 
    borderRadius: 10,
    borderWidth: 1,
    borderColor: paletteV2.neutralLight,
    elevation: 1,
  },
  documentName: {
    flex: 1,
    fontSize: 15,
    color: paletteV2.textPrimaryOnLight,
    fontWeight: '600',
    marginLeft: 14,
  },
  viewButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 7,
    paddingHorizontal: 12,
    borderRadius: 20, 
    backgroundColor: paletteV2.primaryLight,
  },
  viewButtonText: {
    color: paletteV2.primaryDark,
    fontWeight: 'bold',
    fontSize: 13,
  },
  pendingTag: {
    paddingVertical: 7,
    paddingHorizontal: 12,
    borderRadius: 20, 
    backgroundColor: paletteV2.warningMain,
  },
  pendingTagText: {
    color: paletteV2.neutralDark, 
    fontWeight: 'bold',
    fontSize: 13,
  },
  webviewHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 10,
    backgroundColor: paletteV2.surface,
    borderBottomWidth: 1,
    borderBottomColor: paletteV2.neutralLight,
  },
  webviewTitle: {
    flex: 1,
    fontSize: 18,
    fontWeight: 'bold',
    marginLeft: 16, 
    color: paletteV2.textPrimaryOnLight,
  },
  pdfLoaderContainer:{ 
    ...StyleSheet.absoluteFillObject, 
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(248, 249, 250, 0.85)', 
    zIndex: 10, 
  },
  downloadButton: {
    position: 'absolute',
    right: 25,
    bottom: 35,
    backgroundColor: paletteV2.accentMain,
    borderRadius: 35, 
    width: 70,
    height: 70,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 5,
    shadowColor: paletteV2.neutralDark,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.25,
    shadowRadius: 5,
  },
  modalOverlay_Profile: { 
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
  },
  adminMenuOuterContainer_Profile: { 
    position: 'absolute',
    top: 55, 
    right: 15,
    backgroundColor: paletteV2.surface,
    borderRadius: 10,
    elevation: 8, 
    shadowColor: paletteV2.neutralDark, 
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    minWidth: 200, 
  },
});